[package]
name = "tracing-none-or-current"
version.workspace = true
description = "Checks or_current on Span::none"
edition.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
dylint_linting.workspace = true
dylint_support.workspace = true
tracing_support.workspace = true
[dev-dependencies]
dylint_testing.workspace = true
tracing.workspace = true

[[example]]
name = "main"
path = "ui/main.rs"

[features]
rlib = ["dylint_linting/constituent"]

[lints]
workspace = true

[package.metadata.rust-analyzer]
rustc_private = true
