[package]
name = "manual_try_for_each_loop"
version.workspace = true
description = "A lint to check for fallible loops that can use Iterator::try_for_each"
edition.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
dylint_linting.workspace = true
dylint_support.workspace = true
[dev-dependencies]
dylint_testing.workspace = true

[features]
rlib = ["dylint_linting/constituent"]

[lints]
workspace = true

[package.metadata.rust-analyzer]
rustc_private = true
