[package]
name = "dependency_full_semver_versions"
version.workspace = true
description = "A lint to check for dependency versions without full semver"
edition.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cargo_support.workspace = true
dylint_linting.workspace = true
dylint_support.workspace = true
[dev-dependencies]
dylint_testing.workspace = true

[features]
rlib = ["dylint_linting/constituent"]

[lints]
workspace = true

[package.metadata.rust-analyzer]
rustc_private = true
