[package]
name = "bevy-inherited-visibility-mutation-query"
version.workspace = true
description = "A lint that checks mutable queries of Bevy-managed InheritedVisibility"
edition.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bevy-support.workspace = true
dylint-support.workspace = true
dylint_linting.workspace = true

[dev-dependencies]
dylint_testing.workspace = true

bevy = { workspace = true, features = ["bevy_camera", "std"] }
[[example]]
name = "main"
path = "ui/main.rs"
test = false

[features]
rlib = ["dylint_linting/constituent"]

[lints]
workspace = true

[package.metadata.rust-analyzer]
rustc_private = true

[package.metadata.dylint]
category = "bevy"
