[package]
name = "insta"
version.workspace = true
description = "Rust review lints for Insta snapshot API misuse"
edition.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
dylint_linting.workspace = true
insta-allow-empty-glob = { workspace = true, features = ["rlib"] }
insta-binary-snapshot-missing-extension = { workspace = true, features = [
  "rlib",
] }
insta-bind-to-scope-in-async = { workspace = true, features = ["rlib"] }
insta-compact-json-snapshot = { workspace = true, features = ["rlib"] }
insta-content-direct-match = { workspace = true, features = ["rlib"] }
insta-deprecated-assert-display = { workspace = true, features = ["rlib"] }
insta-empty-description = { workspace = true, features = ["rlib"] }
insta-empty-filter-pattern = { workspace = true, features = ["rlib"] }
insta-empty-input-file = { workspace = true, features = ["rlib"] }
insta-empty-snapshot-path = { workspace = true, features = ["rlib"] }
insta-empty-snapshot-suffix = { workspace = true, features = ["rlib"] }
insta-glob-parent-traversal = { workspace = true, features = ["rlib"] }
insta-json-snapshot = { workspace = true, features = ["rlib"] }
insta-no-module-prefix = { workspace = true, features = ["rlib"] }
insta-noop-filter = { workspace = true, features = ["rlib"] }
insta-redundant-content-resolve-inner = { workspace = true, features = [
  "rlib",
] }
insta-settings-bind-future = { workspace = true, features = ["rlib"] }
insta-settings-new = { workspace = true, features = ["rlib"] }
insta-settings-raw-info = { workspace = true, features = ["rlib"] }
insta-snapshot-in-loop = { workspace = true, features = ["rlib"] }
[features]
rlib = ["dylint_linting/constituent"]

[lints]
workspace = true

[package.metadata.rust-analyzer]
rustc_private = true
