[package]
name = "tokio-zero-capacity-channel"
version.workspace = true
description = "A lint to check for zero-capacity Tokio channels"
edition.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
dylint-support.workspace = true
dylint_linting.workspace = true
tokio-support.workspace = true
[dev-dependencies]
dylint_testing.workspace = true
tokio.workspace = true

[[example]]
name = "main"
path = "ui/main.rs"
test = false

[features]
rlib = ["dylint_linting/constituent"]

[lints]
workspace = true

[package.metadata.rust-analyzer]
rustc_private = true

[package.metadata.dylint]
category = "tokio"
