[workspace.metadata.dylint]
libraries = [
    { path = "lints/cargo" },
    { path = "lints/complexity" },
    { path = "lints/correctness" },
    { path = "lints/crates" },
    { path = "lints/maintainability" },
    { path = "lints/perf" },
    { path = "lints/restriction" },
    { path = "lints/style" },
    { path = "lints/suspicious" },
]
