[package]
name = "strum"
version.workspace = true
description = "Rust review lints for Strum enum representation contracts"
edition.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
dylint_linting.workspace = true
strum_enum_representation = { package = "strum-enum-representation", path = "strum-enum-representation", features = ["rlib"] }

[features]
rlib = ["dylint_linting/constituent"]

[lints]
workspace = true

[package.metadata.rust-analyzer]
rustc_private = true
