#![expect(
    clippy::disallowed_methods,
    clippy::disallowed_types,
    reason = "the synchronous integration harness owns fixture files and child processes"
)]
#![allow(
    unused_crate_dependencies,
    reason = "the runner package embeds lint libraries that these tests do not import"
)]

//! Integration tests for the `sagan-lints` runner binary.
//!
//! Each test runs the compiled runner against a small fixture repository with
//! isolated cache directories. The fixtures cover bundled lint listing, the
//! embedded compiler driver, strict Clippy, automatic fixes, changed-range
//! filtering, and toolchain compatibility diagnostics.

use std::{
    fs,
    path::{Path, PathBuf},
    process::Command,
};

use tempfile::TempDir;

/// Isolated cache and scratch directories for one runner invocation sequence.
struct Sandbox {
    /// Temporary root removed when the test finishes.
    root: TempDir,
}

/// Captured result of one runner process.
struct RunOutput {
    /// Whether the runner exited successfully.
    success: bool,
    /// Combined standard output and standard error.
    text: String,
}

impl Sandbox {
    /// Create an empty sandbox.
    fn new() -> Self {
        Self {
            root: tempfile::tempdir().expect("temporary directory should be available"),
        }
    }

    /// Resolve a path below the sandbox root.
    fn path(&self, relative: &str) -> PathBuf {
        self.root.path().join(relative)
    }

    /// Run the runner with sandboxed cache directories.
    fn run(&self, args: &[&str]) -> RunOutput {
        let output = Command::new(env!("CARGO_BIN_EXE_sagan-lints"))
            .args(args)
            .env("SAGAN_LINTS_CACHE_DIR", self.path("cache"))
            .env("XDG_CACHE_HOME", self.path("xdg-cache"))
            .output()
            .expect("the runner should start");
        let mut text = String::from_utf8_lossy(&output.stdout).into_owned();
        text.push_str(&String::from_utf8_lossy(&output.stderr));
        RunOutput {
            success: output.status.success(),
            text,
        }
    }
}

/// Repository-relative path of a checked-in fixture.
fn fixture(relative: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(relative)
}

/// Write one file, creating its parent directories.
fn write(path: &Path, contents: &str) {
    fs::create_dir_all(path.parent().expect("fixture files should have a parent"))
        .expect("fixture directory should be writable");
    fs::write(path, contents).expect("fixture file should be writable");
}

/// Run one Git command in a repository and require success.
fn git(repository: &Path, args: &[&str]) {
    let status = Command::new("git")
        .arg("-C")
        .arg(repository)
        .args(args)
        .status()
        .expect("git should start");
    assert!(status.success(), "git {args:?} should succeed");
}

/// Write a single-package Cargo repository pinned to the runner's toolchain and commit it.
fn package_repository(
    repository: &Path,
    name: &str,
    manifest_extra: &str,
    source_path: &str,
    source: &str,
) {
    write(
        &repository.join("Cargo.toml"),
        &format!(
            "[package]\nname = \"{name}\"\nversion = \"0.1.0\"\nedition = \"2024\"\n{manifest_extra}"
        ),
    );
    write(
        &repository.join("Cargo.lock"),
        &format!(
            "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"{name}\"\nversion = \"0.1.0\"\n"
        ),
    );
    write(
        &repository.join("rust-toolchain.toml"),
        "[toolchain]\nchannel = \"nightly-2026-07-15\"\n",
    );
    write(&repository.join(source_path), source);
    git(repository, &["init", "-q"]);
    commit_all(repository, "baseline");
}

/// Stage and commit every change with a synthetic identity.
fn commit_all(repository: &Path, message: &str) {
    git(repository, &["add", "--all"]);
    git(
        repository,
        &[
            "-c",
            "user.name=Synthetic Lint Fixture",
            "-c",
            "user.email=synthetic@example.invalid",
            "commit",
            "-qm",
            message,
        ],
    );
}

/// Run `--list-private-lints` against an empty workspace and require success.
fn list_private_lints(sandbox: &Sandbox) -> RunOutput {
    // Create an empty Git workspace so listing needs no package build.
    let repository = sandbox.path("empty");
    write(
        &repository.join("Cargo.toml"),
        "[workspace]\nresolver = \"2\"\nmembers = []\n",
    );
    git(&repository, &["init", "-q"]);

    // List every default category and require the runner to succeed.
    let output = sandbox.run(&[
        "--repo",
        repository.to_str().expect("sandbox path should be UTF-8"),
        "--list-private-lints",
    ]);
    assert!(output.success, "{}", output.text);
    output
}

/// Collect the lint name of every lint crate below `dir` that has a `ui/` fixture directory.
///
/// A lint crate's package name, with `-` replaced by `_`, is its lint name.
fn ui_lint_crate_names(dir: &Path, names: &mut Vec<String>) {
    let manifest = dir.join("Cargo.toml");
    // Record this directory when it is a lint crate with UI fixtures.
    if dir.join("ui").is_dir() && manifest.is_file() {
        let contents = fs::read_to_string(&manifest).expect("lint manifest should be readable");
        let name = contents
            .lines()
            .find_map(|line| line.strip_prefix("name = \""))
            .and_then(|rest| rest.strip_suffix('"'))
            .expect("lint manifest should declare a package name");
        names.push(name.replace('-', "_"));
    }
    // Descend into child directories other than build output.
    for entry in fs::read_dir(dir).expect("lint directory should be readable") {
        let path = entry
            .expect("lint directory entry should be readable")
            .path();
        if path.is_dir() && path.file_name().is_some_and(|name| name != "target") {
            ui_lint_crate_names(&path, names);
        }
    }
}

/// The runner lists lints from repository, crate-specific, and style libraries.
#[test]
fn lists_bundled_private_lints() {
    // List the bundled lints from an empty workspace.
    let sandbox = Sandbox::new();
    let output = list_private_lints(&sandbox);

    // Sample one lint from a repository, a crate-specific, and a style library.
    for lint in [
        "dependency_full_semver_versions",
        "bevy_main_return_without_app_exit",
        "ad_hoc_from_str",
    ] {
        // Print the full listing so a missing name is easy to diagnose.
        assert!(
            output.text.contains(lint),
            "missing {lint}:\n{}",
            output.text
        );
    }
}

/// Every lint crate with UI fixtures is registered in a bundled category library.
#[test]
fn lists_every_lint_crate_with_ui_fixtures() {
    // Discover lint crates from the source tree instead of a hand-kept list.
    let mut names = Vec::new();
    ui_lint_crate_names(
        &Path::new(env!("CARGO_MANIFEST_DIR")).join("lints"),
        &mut names,
    );
    assert!(!names.is_empty(), "no lint crates with ui/ were found");

    // Ask the runner which lints its bundled category libraries register.
    let sandbox = Sandbox::new();
    let output = list_private_lints(&sandbox);

    // Match whole list rows so a lint name that prefixes another cannot hide a gap.
    let listed: Vec<&str> = output
        .text
        .lines()
        .filter_map(|line| line.split_whitespace().next())
        .collect();
    // Report every unregistered crate at once.
    let missing: Vec<&String> = names
        .iter()
        .filter(|name| !listed.contains(&name.as_str()))
        .collect();
    assert!(
        missing.is_empty(),
        "lint crates missing from --list-private-lints: {missing:?}"
    );
}

/// A dry run plans Clippy and the embedded driver without external Dylint helpers.
#[test]
fn dry_run_uses_embedded_driver() {
    let sandbox = Sandbox::new();
    let target = sandbox.path("target");
    let output = sandbox.run(&[
        "--repo",
        fixture("cargo-install-target")
            .to_str()
            .expect("fixture path should be UTF-8"),
        "--no-workspace",
        "--fast",
        "--target-dir",
        target.to_str().expect("sandbox path should be UTF-8"),
        "--dylint-category",
        "suspicious",
        "--heartbeat-seconds",
        "0",
        "--dry-run",
    ]);

    assert!(output.success, "{}", output.text);
    assert!(output.text.contains(" clippy "), "{}", output.text);
    assert!(output.text.contains(" check"), "{}", output.text);
    assert!(!output.text.contains("cargo-dylint"), "{}", output.text);
    assert!(!output.text.contains("dylint-link"), "{}", output.text);
}

/// A bundled private lint rejects the fixture's string error result.
#[test]
fn bundled_private_lint_rejects_fixture() {
    let sandbox = Sandbox::new();
    let target = sandbox.path("target");
    let output = sandbox.run(&[
        "--repo",
        fixture("cargo-install-target")
            .to_str()
            .expect("fixture path should be UTF-8"),
        "--no-workspace",
        "--fast",
        "--target-dir",
        target.to_str().expect("sandbox path should be UTF-8"),
        "--skip-clippy",
        "--dylint-category",
        "suspicious",
        "--heartbeat-seconds",
        "0",
    ]);

    assert!(!output.success, "{}", output.text);
    assert!(
        output.text.contains("string_error_result"),
        "{}",
        output.text
    );
}

/// Strict Clippy rejects the fixture's `unwrap` call.
#[test]
fn strict_clippy_rejects_fixture() {
    let sandbox = Sandbox::new();
    let target = sandbox.path("target");
    let output = sandbox.run(&[
        "--repo",
        fixture("cargo-install-target")
            .to_str()
            .expect("fixture path should be UTF-8"),
        "--no-workspace",
        "--fast",
        "--target-dir",
        target.to_str().expect("sandbox path should be UTF-8"),
        "--skip-dylint",
        "--heartbeat-seconds",
        "0",
    ]);

    assert!(!output.success, "{}", output.text);
    assert!(
        output.text.contains("clippy::unwrap-used"),
        "{}",
        output.text
    );
}

/// Fix mode rewrites machine-applicable findings and a second run no longer reports them.
#[test]
fn fix_mode_applies_machine_applicable_suggestions() {
    let sandbox = Sandbox::new();
    let working_copy = sandbox.path("input");
    let input = fixture("lint-fixer/input");
    write(
        &working_copy.join("Cargo.toml"),
        &fs::read_to_string(input.join("Cargo.toml")).expect("fixture manifest should be readable"),
    );
    write(
        &working_copy.join("src/main.rs"),
        &fs::read_to_string(input.join("src/main.rs")).expect("fixture source should be readable"),
    );
    let repository = working_copy.to_str().expect("sandbox path should be UTF-8");
    let fix_args = ["--repo", repository, "--fast", "--skip-clippy", "--fix"];

    let fixed = sandbox.run(&fix_args);
    assert!(fixed.success, "{}", fixed.text);
    let expected = fs::read_to_string(fixture("lint-fixer/expected/src/main.rs"))
        .expect("expected fixture should be readable");
    let actual = fs::read_to_string(working_copy.join("src/main.rs"))
        .expect("fixed source should be readable");
    assert_eq!(actual, expected);

    // The fixed source must no longer trigger either rewritten lint.
    let checked = sandbox.run(&fix_args[..4]);
    assert!(
        !checked
            .text
            .contains("internal import should start with `self::`"),
        "{}",
        checked.text
    );
    assert!(
        !checked
            .text
            .contains("outer `doc` attribute can be written as `///`"),
        "{}",
        checked.text
    );
}

/// A clean external repository passes without build output or Git changes inside it.
#[test]
fn clean_repository_passes_without_writing_into_it() {
    let sandbox = Sandbox::new();
    let repository = sandbox.path("clean");
    package_repository(
        &repository,
        "synthetic-clean-boundary",
        "rust-version = \"1.98.1\"\n",
        "src/main.rs",
        "#![allow(missing_docs, reason = \"synthetic fixture has no public API\")]\n\nfn main() {}\n",
    );

    let output = sandbox.run(&[
        "--repo",
        repository.to_str().expect("sandbox path should be UTF-8"),
        "--fast",
        "--heartbeat-seconds",
        "0",
    ]);

    assert!(output.success, "{}", output.text);
    assert!(
        output.text.contains("clippy: finished in"),
        "{}",
        output.text
    );
    assert!(
        output.text.contains("dylint: finished in"),
        "{}",
        output.text
    );
    assert!(!repository.join("target").exists());
    let status = Command::new("git")
        .arg("-C")
        .arg(&repository)
        .args(["status", "--short"])
        .output()
        .expect("git should start");
    assert!(
        status.stdout.is_empty(),
        "{}",
        String::from_utf8_lossy(&status.stdout)
    );
}

/// Library source whose `collect` return triggers `collect_return`.
const CHANGED_RANGE_BASELINE: &str = "pub fn baseline(values: &[u64]) -> Vec<u64> {\n    values.iter().map(|value| value * 2).collect()\n}\n";

/// Run the complexity lints on a repository, optionally limited to the last commit.
fn run_complexity(sandbox: &Sandbox, repository: &Path, last_commit_only: bool) -> RunOutput {
    let mut args = vec![
        "--repo",
        repository.to_str().expect("sandbox path should be UTF-8"),
        "--fast",
        "--skip-clippy",
        "--dylint-category",
        "complexity",
        "--heartbeat-seconds",
        "0",
    ];
    if last_commit_only {
        args.extend(["--changed-range", "HEAD^..HEAD"]);
    }
    sandbox.run(&args)
}

/// A changed range reports findings on changed lines only.
#[test]
fn changed_range_reports_only_changed_lines() {
    let sandbox = Sandbox::new();
    let repository = sandbox.path("diff");
    let library = repository.join("src/lib.rs");
    let baseline = CHANGED_RANGE_BASELINE;
    package_repository(
        &repository,
        "synthetic-diff-boundary",
        "",
        "src/lib.rs",
        baseline,
    );

    // The full run reports the baseline finding.
    let full = run_complexity(&sandbox, &repository, false);
    assert!(!full.success, "{}", full.text);
    assert!(full.text.contains("collect_return"), "{}", full.text);

    // An unrelated change leaves the baseline finding outside the range.
    let unrelated_source = format!("{baseline}\n// unrelated source change\n");
    write(&library, &unrelated_source);
    commit_all(&repository, "unrelated source change");
    let unrelated = run_complexity(&sandbox, &repository, true);
    assert!(unrelated.success, "{}", unrelated.text);
    assert!(
        unrelated.text.contains("no diagnostics on changed lines"),
        "{}",
        unrelated.text
    );
    assert!(
        !unrelated.text.contains("collect_return"),
        "{}",
        unrelated.text
    );

    // A new finding inside the range is reported exactly once.
    write(
        &library,
        &format!(
            "{unrelated_source}\npub fn changed(values: &[u64]) -> Vec<u64> {{\n    values.iter().map(|value| value + 1).collect()\n}}\n"
        ),
    );
    commit_all(&repository, "changed lint boundary");
    let changed = run_complexity(&sandbox, &repository, true);
    assert!(!changed.success, "{}", changed.text);
    assert_eq!(
        changed.text.matches("collect_return").count(),
        1,
        "{}",
        changed.text
    );
}

/// A package that requires a newer compiler fails with the required version.
#[test]
fn incompatible_rust_version_is_reported() {
    let sandbox = Sandbox::new();
    let repository = sandbox.path("toolchain");
    package_repository(
        &repository,
        "synthetic-toolchain-boundary",
        "rust-version = \"1.999.0\"\n",
        "src/main.rs",
        "fn main() {}\n",
    );

    let output = sandbox.run(&[
        "--repo",
        repository.to_str().expect("sandbox path should be UTF-8"),
        "--fast",
        "--skip-dylint",
        "--heartbeat-seconds",
        "0",
    ]);

    assert!(!output.success, "{}", output.text);
    assert!(
        output.text.contains("requires rustc 1.999.0"),
        "{}",
        output.text
    );
}
