#![allow(dead_code)]

use std::convert::TryFrom;
use std::str::FromStr;

struct UserId(String);
struct ParseUserIdError;
struct Port(u16);

// Local macros that share a logging macro's name are not logging calls.
macro_rules! warn {
    ($($tokens:tt)*) => {
        let _ = format_args!($($tokens)*);
    };
}

macro_rules! my_warn {
    ($($tokens:tt)*) => {
        let _ = format_args!($($tokens)*);
    };
}

// A local wrapper around a real logging macro still logs.
macro_rules! audit {
    ($message:literal) => {
        tracing::info!($message)
    };
}

// Impls generated by a macro are skipped because the call site cannot be edited.
macro_rules! logged_from {
    ($ty:ident) => {
        impl From<u8> for $ty {
            fn from(value: u8) -> Self {
                eprintln!("generated conversion");
                $ty(value.to_string())
            }
        }
    };
}

logged_from!(UserId);

mod helpers {
    pub fn warn(_message: &str) {}
}

impl From<String> for UserId {
    fn from(value: String) -> Self {
        // tracing::warn!("comment text is not a call");
        let _text = "eprintln!(\"string text is not a call\")";
        warn!("local macro named warn");
        my_warn!("local macro with a longer name");
        helpers::warn("helper outside a logging namespace");
        Self(value)
    }
}

impl TryFrom<&str> for UserId {
    type Error = ParseUserIdError;

    fn try_from(value: &str) -> Result<Self, Self::Error> {
        audit!("wrapped logging macro");
        Ok(Self(value.to_owned()))
    }
}

impl FromStr for UserId {
    type Err = ParseUserIdError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        value
            .parse::<u8>()
            .map_err(|error| {
                tracing::debug!(%error, "logging inside a closure");
                ParseUserIdError
            })
            .map(|_| Self(value.to_owned()))
    }
}

impl TryFrom<i32> for Port {
    type Error = ParseUserIdError;

    fn try_from(value: i32) -> Result<Self, Self::Error> {
        use tracing::event;
        event!(tracing::Level::WARN, value, "event macro through an import");
        u16::try_from(value).map(Self).map_err(|_| ParseUserIdError)
    }
}

impl Port {
    fn new(value: u16) -> Self {
        eprintln!("inherent methods are not conversions");
        Self(value)
    }
}

impl From<u16> for Port {
    fn from(value: u16) -> Self {
        (|| ())();
        let make = |value| Self(value);
        (make)(value)
    }
}

fn main() {}
