[package]
name = "serde"
version.workspace = true
description = "Rust review lints for Serde API misuse"
edition.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
dylint_linting.workspace = true
serde_all_fields_default = { workspace = true, features = ["rlib"] }
serde_borrow_redundant_str_bytes = { workspace = true, features = ["rlib"] }
serde_cow_missing_borrow = { workspace = true, features = ["rlib"] }
serde_deserialize_any_portability = { workspace = true, features = ["rlib"] }
serde_expecting_style = { workspace = true, features = ["rlib"] }
serde_fallback_missing_other = { workspace = true, features = ["rlib"] }
serde_flatten_deny_unknown_fields = { workspace = true, features = ["rlib"] }
serde_inert_directional_attr = { workspace = true, features = ["rlib"] }
serde_manual_rename_all = { workspace = true, features = ["rlib"] }
serde_serialize_str_to_string = { workspace = true, features = ["rlib"] }
serde_skip_serializing_roundtrip = { workspace = true, features = ["rlib"] }
serde_skip_serializing_variant_error = { workspace = true, features = ["rlib"] }
serde_untagged_missing_expecting = { workspace = true, features = ["rlib"] }

[features]
rlib = ["dylint_linting/constituent"]

[lints]
workspace = true

[package.metadata.rust-analyzer]
rustc_private = true
