[package]
name = "target-and-dotted"
version = "0.1.0"
edition = "2024"

[dependencies]
dotted_dep.package = "bad_dep"
dotted_dep.path = "../bad_dep"
dotted_dep.version = "0.1.0"
path_only_dep = { path = "../path_only_dep" }

[target.'cfg(unix)'.dependencies]
target_bad = { package = "bad_dep", path = "../bad_dep", version = "0.1.0" }

[lib]
path = "lib.rs"

[workspace]
resolver = "3"
