#![feature(rustc_private)]
#![expect(
    unused_crate_dependencies,
    reason = "this test crate imports only the declaration macro under test"
)]

//! This integration test checks the lint declaration generated by
//! `documented_late_lint!`. Compilation checks compatibility with rustc's
//! late-pass traits. Runtime assertions verify the generated pass name and
//! the registered lint name consumed by the lint driver. The declaration
//! uses the warning level and defines one lint with no custom pass state.

extern crate rustc_driver as _;

use rustc_lint::{LateLintPass, LintPass as _};

dylint_support::documented_late_lint! {
    /// Demonstration lint used to exercise the generated declaration.
    pub DEMO_LINT,
    Warn,
    "demonstration lint",
    DemoPass
}

impl LateLintPass<'_> for DemoPass {}

/// The generated pass reports its type name and its single lint.
#[test]
fn generated_pass_describes_its_lint() {
    let lints = DemoPass.get_lints();

    assert_eq!(DemoPass.name(), "DemoPass");
    assert_eq!(
        lints
            .iter()
            .map(|lint| lint.name_lower())
            .collect::<Vec<_>>(),
        ["demo_lint"]
    );
}
