[alias]
xtask = "run --package xtask --"

# Development build policy. Cargo configuration supports profile overrides.
# https://doc.rust-lang.org/cargo/reference/config.html#profile
[profile.dev]
debug = "line-tables-only"
incremental = false

[target.'cfg(all())']
linker = "dylint-link"
