#![allow(dead_code)]

use std::rc::Rc;
use std::sync::Arc;

struct Error;

enum Value {
    Text(String),
    Number(u64),
}

struct Payload {
    raw: String,
    shared: Arc<str>,
    local: Rc<String>,
    count: u32,
    value: Value,
}

impl Payload {
    fn as_str(&self) -> &str {
        &self.raw
    }

    // Cheap borrowed accessors may return `Option` or `Result`.
    fn as_text(&self) -> Option<&str> {
        match &self.value {
            Value::Text(text) => Some(text),
            Value::Number(_) => None,
        }
    }

    fn as_number(&self) -> Result<u64, &Error> {
        match self.value {
            Value::Number(number) => Ok(number),
            Value::Text(_) => Err(&Error),
        }
    }

    // Copy and reference-counted clones are cheap.
    fn as_count(&self) -> u32 {
        self.count.clone()
    }

    fn as_shared(&self) -> Arc<str> {
        Arc::clone(&self.shared)
    }

    fn as_local(&self) -> Rc<String> {
        self.local.clone()
    }

    // Text in comments and strings is not work: .clone() format!(..) .parse()
    fn as_label(&self) -> &'static str {
        "self.raw.clone() and format!(\"{}\")"
    }

    fn as_called(&self) -> u32 {
        (|| self.count)()
    }

    fn as_parsed(&self) -> Result<u64, Error> {
        self.raw.parse::<u64>().map_err(|_| Error)
    }

    fn as_owned_string(&self) -> String {
        Clone::clone(&self.raw)
    }

    fn as_question(&self) -> Result<u64, Error> {
        let number = self.as_number().map_err(|_| Error)?;
        Ok(number)
    }

    fn as_borrowed_owned(&self) -> String {
        self.as_str().to_owned()
    }

    fn as_converted(&self) -> Vec<u8> {
        Vec::from(self.as_str())
    }

    fn as_in_closure(&self) -> Option<String> {
        self.as_text().map(|text| text.to_string())
    }
}

// Methods generated by a macro are not checked.
macro_rules! owned_accessor {
    ($name:ident) => {
        impl Payload {
            fn $name(&self) -> String {
                self.raw.clone()
            }
        }
    };
}

owned_accessor!(as_generated);

trait Render {
    fn as_rendered(&self) -> String {
        String::new().clone()
    }
}

fn as_free_function(raw: &str) -> String {
    raw.to_owned()
}

fn main() {}
