[package]
name = "schemars-recursive-inline-schema"
version.workspace = true
description = "A lint to check for recursive Schemars schemas marked inline"
edition.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
dylint-support.workspace = true
dylint_linting.workspace = true
schemars-support.workspace = true
[dev-dependencies]
dylint_testing.workspace = true
schemars.workspace = true

[[example]]
name = "main"
path = "ui/main.rs"
test = false

[features]
rlib = ["dylint_linting/constituent"]

[lints]
workspace = true

[package.metadata.rust-analyzer]
rustc_private = true

[package.metadata.dylint]
category = "schemars"
