[package]
name = "schemars-redundant-serde-rename-all"
version.workspace = true
description = "Checks redundant Schemars rename_all attributes"
edition.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
dylint_linting.workspace = true
dylint_support.workspace = true
schemars_support.workspace = true
[dev-dependencies]
dylint_testing.workspace = true
schemars.workspace = true
serde.workspace = true

[[example]]
name = "main"
path = "ui/main.rs"

[features]
rlib = ["dylint_linting/constituent"]

[lints]
workspace = true

[package.metadata.rust-analyzer]
rustc_private = true
