//! AST helpers for thiserror lints that must run before type checking.
//!
//! Some thiserror mistakes make the derived code fail to type-check, so a late
//! lint never runs on them. These helpers work on the expanded AST instead.
//! thiserror 2 implements `::thiserror::__privateNN::Error` for the derived
//! type; an implementation with that trait path that a derive macro generated
//! proves the type derives `thiserror::Error`, whatever its import spelling.

use crate::format::ErrorAttr;
use rustc_ast::{Attribute, FieldDef, Item, ItemKind, ModKind, TyKind, VariantData};
use rustc_span::{
    Span, Symbol,
    hygiene::{ExpnKind, MacroKind},
    source_map::SourceMap,
};

/// One struct or enum variant of a type that derives `thiserror::Error`.
#[derive(Clone, Copy, Debug)]
pub struct EarlyShape<'a> {
    /// The attributes that hold `#[error]` for this struct or variant.
    pub attrs: &'a [Attribute],
    /// The fields of the struct or variant.
    pub fields: &'a [FieldDef],
}

/// Call `check` with the items of every loaded module, starting at the crate root.
///
/// # Examples
///
/// ```rust
/// # use thiserror_support::early::for_each_module;
/// let _ = for_each_module;
/// ```
pub fn for_each_module<'a>(items: &'a [Box<Item>], check: &mut impl FnMut(&'a [Box<Item>])) {
    check(items);
    for item in items {
        if let ItemKind::Mod(_, _, ModKind::Loaded(nested, ..)) = &item.kind {
            for_each_module(nested, check);
        }
    }
}

/// Return the shapes of every type in one module that derives `thiserror::Error`.
#[must_use]
///
/// # Examples
///
/// ```rust
/// # use thiserror_support::early::thiserror_shapes;
/// let _ = thiserror_shapes;
/// ```
pub fn thiserror_shapes(items: &[Box<Item>]) -> Vec<EarlyShape<'_>> {
    let derived = items
        .iter()
        .filter_map(|item| thiserror_impl_self_name(item))
        .collect::<Vec<_>>();
    let mut shapes_found = Vec::new();
    for item in items.iter().filter(|item| {
        item.kind
            .ident()
            .is_some_and(|ident| derived.contains(&ident.name))
    }) {
        shapes_found.extend(shapes(item));
    }
    shapes_found
}

/// Return the shapes of one struct or enum.
fn shapes(item: &Item) -> Vec<EarlyShape<'_>> {
    if let ItemKind::Struct(_, _, data) = &item.kind {
        vec![shape(&item.attrs, data)]
    } else if let ItemKind::Enum(_, _, definition) = &item.kind {
        definition
            .variants
            .iter()
            .map(|variant| shape(&variant.attrs, &variant.data))
            .collect()
    } else {
        Vec::new()
    }
}

/// Build one shape from attributes and variant data.
fn shape<'a>(attrs: &'a [Attribute], data: &'a VariantData) -> EarlyShape<'a> {
    EarlyShape {
        attrs,
        fields: data.fields(),
    }
}

/// Return the self type name of an `Error` implementation generated by thiserror.
fn thiserror_impl_self_name(item: &Item) -> Option<Symbol> {
    let ItemKind::Impl(implementation) = &item.kind else {
        return None;
    };
    let expansion = item.span.ctxt().outer_expn_data();
    if !matches!(expansion.kind, ExpnKind::Macro(MacroKind::Derive, _)) {
        return None;
    }
    // thiserror 2 spells the trait as `::thiserror::__privateNN::Error`.
    let trait_path = &implementation.of_trait.as_ref()?.trait_ref.path;
    let names = trait_path
        .segments
        .iter()
        .map(|segment| segment.ident.name.as_str())
        .collect::<Vec<_>>();
    if !matches!(names.as_slice(), ["{{root}}", "thiserror", .., "Error"]) {
        return None;
    }
    let TyKind::Path(None, self_path) = &implementation.self_ty.kind else {
        return None;
    };
    Some(self_path.segments.last()?.ident.name)
}

/// Return the parsed `#[error(...)]` attributes in an attribute list.
#[must_use]
///
/// # Examples
///
/// ```rust
/// # use thiserror_support::early::error_attrs;
/// let _ = error_attrs;
/// ```
pub fn error_attrs(source_map: &SourceMap, attrs: &[Attribute]) -> Vec<(Span, ErrorAttr)> {
    let mut parsed = Vec::new();
    for attr in attrs
        .iter()
        .filter(|attr| attr.has_name(Symbol::intern("error")))
    {
        let Some(text) = source_map.span_to_snippet(attr.span).ok() else {
            continue;
        };
        let Some(error) = ErrorAttr::parse(&text) else {
            continue;
        };
        parsed.push((attr.span, error));
    }
    parsed
}

/// Return whether a field has a single-segment attribute with this name.
#[must_use]
///
/// # Examples
///
/// ```rust
/// # use thiserror_support::early::has_attr;
/// let _ = has_attr;
/// ```
pub fn has_attr(field: &FieldDef, name: &str) -> bool {
    field
        .attrs
        .iter()
        .any(|attr| attr.has_name(Symbol::intern(name)))
}

/// Return whether a field is named exactly `name`, without raw-identifier syntax.
#[must_use]
///
/// # Examples
///
/// ```rust
/// # use thiserror_support::early::is_field_named;
/// let _ = is_field_named;
/// ```
pub fn is_field_named(source_map: &SourceMap, field: &FieldDef, name: &str) -> bool {
    field.ident.is_some_and(|ident| {
        ident.name.as_str() == name
            && source_map
                .span_to_snippet(ident.span)
                .is_ok_and(|snippet| snippet == name)
    })
}
