#![feature(rustc_private)]
#![warn(unused_extern_crates)]
#![doc(hidden)]

//! Shared semantic helpers for thiserror-specific private lints.
//!
//! Late lints prove that a type derives `thiserror::Error` through the
//! `std::error::Error` implementation that thiserror's derive macro generated,
//! so imports, aliases, and glob imports do not matter. Early lints, which run
//! on code that fails to type-check, recognize the implementation the derive
//! generated by its expansion and its `::thiserror` trait path. Both read
//! `#[error(...)]` attributes with the same token rules thiserror uses.

extern crate rustc_ast;
extern crate rustc_driver as _;
extern crate rustc_errors;
extern crate rustc_hir;
extern crate rustc_lint;
extern crate rustc_middle;
extern crate rustc_span;

pub mod early;
pub mod format;

use self::format::ErrorAttr;
use dylint_linting as _;
use rustc_errors::{Applicability, DiagDecorator};
use rustc_hir::{FieldDef, HirId, Item, ItemKind, VariantData};
use rustc_lint::{LateContext, Lint, LintContext as _};
use rustc_middle::ty;
use rustc_span::{
    BytePos, Pos as _, Span, Symbol,
    def_id::LocalDefId,
    hygiene::{ExpnKind, MacroKind},
};
use std::ops::Range;

/// The crate that defines thiserror's derive macro in every released version.
const THISERROR_MACRO_CRATE: &str = "thiserror_impl";

/// One struct or enum variant whose `#[error]` attributes thiserror reads.
#[derive(Clone, Copy, Debug)]
pub struct ErrorShape<'tcx> {
    /// The struct item or the variant that holds the `#[error]` attributes.
    pub hir_id: HirId,
    /// The fields of the struct or variant.
    pub fields: &'tcx [FieldDef<'tcx>],
    /// Whether the fields are unnamed tuple fields.
    pub is_tuple: bool,
}

/// Return the structs and variants of a type that derives `thiserror::Error`.
///
/// The result is empty for any other item.
#[must_use]
///
/// # Examples
///
/// ```rust
/// # #![feature(rustc_private)]
/// let _call = |cx, item| {
///     let _ = thiserror_support::thiserror_shapes(cx, item);
/// };
/// ```
pub fn thiserror_shapes<'tcx>(
    cx: &LateContext<'tcx>,
    item: &'tcx Item<'tcx>,
) -> Vec<ErrorShape<'tcx>> {
    let shapes = if let ItemKind::Struct(_, _, data) = &item.kind {
        vec![shape(item.hir_id(), data)]
    } else if let ItemKind::Enum(_, _, definition) = &item.kind {
        definition
            .variants
            .iter()
            .map(|variant| shape(variant.hir_id, &variant.data))
            .collect()
    } else {
        return Vec::new();
    };
    if is_thiserror_derived(cx, item.owner_id.def_id) {
        shapes
    } else {
        Vec::new()
    }
}

/// Build the shape of one struct or variant.
fn shape<'tcx>(hir_id: HirId, data: &'tcx VariantData<'tcx>) -> ErrorShape<'tcx> {
    ErrorShape {
        hir_id,
        fields: data.fields(),
        is_tuple: matches!(data, VariantData::Tuple(..)),
    }
}

/// Return whether thiserror's derive generated the type's `Error` implementation.
fn is_thiserror_derived(cx: &LateContext<'_>, adt: LocalDefId) -> bool {
    let Some(error_trait) = cx.tcx.get_diagnostic_item(Symbol::intern("Error")) else {
        return false;
    };
    let Some(impls) = cx.tcx.all_local_trait_impls(()).get(&error_trait) else {
        return false;
    };
    impls.iter().any(|&impl_id| {
        let self_ty = cx
            .tcx
            .type_of(impl_id)
            .instantiate_identity()
            .skip_norm_wip();
        matches!(self_ty.kind(), ty::Adt(def, _) if def.did() == adt.to_def_id())
            && is_thiserror_expansion(cx, cx.tcx.def_span(impl_id))
    })
}

/// Return whether a span comes from thiserror's derive macro.
fn is_thiserror_expansion(cx: &LateContext<'_>, span: Span) -> bool {
    let expansion = span.ctxt().outer_expn_data();
    matches!(expansion.kind, ExpnKind::Macro(MacroKind::Derive, _))
        && expansion
            .macro_def_id
            .is_some_and(|def_id| cx.tcx.crate_name(def_id.krate).as_str() == THISERROR_MACRO_CRATE)
}

/// Return the parsed `#[error(...)]` attributes on a struct, variant, or enum.
#[must_use]
///
/// # Examples
///
/// ```rust
/// # #![feature(rustc_private)]
/// let _call = |cx, hir_id| {
///     let _ = thiserror_support::error_attrs(cx, hir_id);
/// };
/// ```
pub fn error_attrs(cx: &LateContext<'_>, hir_id: HirId) -> Vec<(Span, ErrorAttr)> {
    let source_map = cx.sess().source_map();
    let mut attrs = Vec::new();
    for span in attr_spans(cx, hir_id, "error") {
        let Some(text) = source_map.span_to_snippet(span).ok() else {
            continue;
        };
        let Some(error) = ErrorAttr::parse(&text) else {
            continue;
        };
        attrs.push((span, error));
    }
    attrs
}

/// Return the span of the first single-segment attribute with this name.
#[must_use]
///
/// # Examples
///
/// ```rust
/// # #![feature(rustc_private)]
/// let _call = |cx, hir_id| {
///     let _ = thiserror_support::find_attr(cx, hir_id, "source");
/// };
/// ```
pub fn find_attr(cx: &LateContext<'_>, hir_id: HirId, name: &str) -> Option<Span> {
    attr_spans(cx, hir_id, name).into_iter().next()
}

/// Return the spans of single-segment attributes with this name.
fn attr_spans(cx: &LateContext<'_>, hir_id: HirId, name: &str) -> Vec<Span> {
    let name = Symbol::intern(name);
    cx.tcx
        .hir_attrs(hir_id)
        .iter()
        .filter(|attr| attr.path().as_slice() == [name])
        .map(rustc_hir::Attribute::span)
        .collect()
}

/// Return whether a field is named exactly `name`, without raw-identifier syntax.
///
/// thiserror treats `r#source` as an ordinary field and `source` as the source,
/// so the raw spelling matters even though both name the same field.
#[must_use]
///
/// # Examples
///
/// ```rust
/// # #![feature(rustc_private)]
/// let _call = |cx, field| {
///     let _ = thiserror_support::is_field_named(cx, field, "source");
/// };
/// ```
pub fn is_field_named(cx: &LateContext<'_>, field: &FieldDef<'_>, name: &str) -> bool {
    field.ident.name.as_str() == name
        && !field.is_positional()
        && cx
            .sess()
            .source_map()
            .span_to_snippet(field.ident.span)
            .is_ok_and(|snippet| snippet == name)
}

/// Map a byte range of an attribute's text to a source span.
#[must_use]
///
/// # Examples
///
/// ```rust
/// # #![feature(rustc_private)]
/// let _call = |span| {
///     let _ = thiserror_support::subspan(span, 0..1);
/// };
/// ```
pub fn subspan(span: Span, range: Range<usize>) -> Span {
    let lo = span.lo();
    span.with_lo(lo + BytePos::from_usize(range.start))
        .with_hi(lo + BytePos::from_usize(range.end))
}

/// An exact rewrite attached to a diagnostic.
#[derive(Clone, Debug)]
pub struct Fix {
    /// The replaced source range.
    pub span: Span,
    /// The replacement text.
    pub replacement: String,
    /// How safe the rewrite is to apply automatically.
    pub applicability: Applicability,
}

/// Emit one diagnostic with either a rewrite or a help message.
///
/// # Examples
///
/// ```rust
/// # #![feature(rustc_private)]
/// let _call = |cx: &rustc_lint::LateContext<'_>, lint, span| {
///     thiserror_support::emit(cx, lint, span, "message", "help", None);
/// };
/// ```
pub fn emit<C: rustc_lint::LintContext>(
    cx: &C,
    lint: &'static Lint,
    span: Span,
    message: &'static str,
    help: &'static str,
    fix: Option<Fix>,
) {
    cx.emit_span_lint(
        lint,
        span,
        DiagDecorator(move |diagnostic| {
            let diagnostic = diagnostic.primary_message(message);
            match fix {
                Some(fix) => {
                    let _configured_suggestion = diagnostic.span_suggestion(
                        fix.span,
                        help,
                        fix.replacement,
                        fix.applicability,
                    );
                }
                None => {
                    let _configured_help = diagnostic.help(help);
                }
            }
        }),
    );
}
