[package]
name = "reqwest-lints"
version.workspace = true
description = "Rust review lints for Reqwest API misuse"
edition.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
dylint_linting.workspace = true
reqwest_blocking_in_async = { workspace = true, features = ["rlib"] }
reqwest_client_in_loop = { workspace = true, features = ["rlib"] }
reqwest_client_wrapped_in_shared_pointer = { workspace = true, features = ["rlib"] }
reqwest_cookie_provider_overridden = { workspace = true, features = ["rlib"] }
reqwest_get_in_loop = { workspace = true, features = ["rlib"] }
reqwest_multipart_manual_content_type = { workspace = true, features = ["rlib"] }
reqwest_retry_invalid_max_extra_load = { workspace = true, features = ["rlib"] }
reqwest_retry_no_budget = { workspace = true, features = ["rlib"] }
reqwest_tls_danger_invalid_certs = { workspace = true, features = ["rlib"] }
reqwest_tls_danger_invalid_hostnames = { workspace = true, features = ["rlib"] }
[features]
rlib = ["dylint_linting/constituent"]

[lints]
workspace = true

[package.metadata.rust-analyzer]
rustc_private = true
