[package]
name = "clap-derive-redundant-action"
version.workspace = true
description = "Checks actions already inferred by Clap derive field types"
edition.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
clap-support.workspace = true
dylint-support.workspace = true
dylint_linting.workspace = true
[dev-dependencies]
clap.workspace = true
dylint_testing.workspace = true

[[example]]
name = "main"
path = "ui/main.rs"
test = false

[features]
rlib = ["dylint_linting/constituent"]

[lints]
workspace = true

[package.metadata.rust-analyzer]
rustc_private = true

[package.metadata.dylint]
category = "clap"
