[package]
name = "thiserror"
version.workspace = true
description = "Rust review lints for thiserror API misuse"
edition.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
dylint_linting.workspace = true
thiserror_named_field_positional_format = { workspace = true, features = ["rlib"] }
thiserror_no_std_path_display = { workspace = true, features = ["rlib"] }
thiserror_raw_field_format = { workspace = true, features = ["rlib"] }
thiserror_redundant_backtrace_attr = { workspace = true, features = ["rlib"] }
thiserror_redundant_from_source = { workspace = true, features = ["rlib"] }
thiserror_redundant_named_source = { workspace = true, features = ["rlib"] }
thiserror_self_display_recursion = { workspace = true, features = ["rlib"] }
thiserror_source_field_opt_out = { workspace = true, features = ["rlib"] }
thiserror_transparent_single_source_display = { workspace = true, features = ["rlib"] }
thiserror_tuple_format_positional_ambiguity = { workspace = true, features = ["rlib"] }

[features]
rlib = ["dylint_linting/constituent"]

[lints]
workspace = true

[package.metadata.rust-analyzer]
rustc_private = true
