[package]
name = "bevy-load-builder-replaced-guard"
version.workspace = true
description = "A lint that checks for repeated Bevy asset load guards"
edition.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bevy-support = { path = "../support" }
dylint-support = { path = "../../../../support/dylint" }
dylint_linting.workspace = true

[dev-dependencies]
bevy_app.workspace = true
bevy_asset.workspace = true
bevy_ecs.workspace = true
dylint_testing.workspace = true

[[example]]
name = "main"
path = "ui/main.rs"

[features]
rlib = ["dylint_linting/constituent"]

[lints]
workspace = true

[package.metadata.rust-analyzer]
rustc_private = true
